### ISSUE TITLE
Add Cpu resources limiting on docker container.

### ISSUE THREAD

**Issue by phamduchongan93** [phamduchongan93/kubernetes-selfhost#1]
```  
resources:
            limits:
              cpus: 0.50
              memory: 512M
            reservations:
              cpus: 0.25
              memory: 128M
```
Sample Code
